apiVersion: v1
kind: Pod
metadata:
  name: "vault"
  namespace: default
  labels:
    app: ""
spec:
  containers:
  - name: "vault-container"
    image: "hashicorp/vault:latest"
    ports:
    - containerPort: 8200
      name:  http