apiVersion: v1
kind: Service
metadata:
  name: lab4
  namespace: default
  labels:
    app: lab4
spec:
  selector:
    app: lab4
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
