apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
        - name: lab2
          image: ifilyaninitmo/itdt-contained-frontend
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_USERNAME
              value: "Lysenko Aleksandra Vladimirovna"
            - name: REACT_APP_COMPANY_NAME
              value: "ITMO"