apiVersion: v1
kind: ConfigMap
metadata:
  name: lab3
data:
  # property-like keys; each key maps to a simple value
  REACT_APP_USERNAME: "Lysenko Aleksandra Vladimirovna"
  REACT_APP_COMPANY_NAME: "ITMO"